### PR TITLE
(MODULES-8379) - Bump of specinfra so that it will work correctly with SLES 15 on Apache

### PR DESCRIPTION
**Pull request by david22swan**

### CODE REVIEW

**Comment by david22swan** [comment]
screen shot 2019-01-11 at 2 03 45 pm

**Comment by david22swan** [comment]
screen shot 2019-01-11 at 2 50 12 pm

**Comment by david22swan** [comment]
screen shot 2019-01-11 at 4 01 26 pm
Test's run with pendings removed.

**Comment by pmcmaw** [comment]
LGTM. Merging.

**Pull request merged**
