### PR TITLE
Adds puppet-debugger gem to list of dependencies

### PR DESCRIPTION
**Pull request by logicminds**
This is required for the upcoming `pdk console` command.

### CODE REVIEW

**Comment by glennsarti** [comment]
Heya @logicminds , I just double checked the gem, and it doesn't appear to test on Ruby 2.1 although the gemsepc is open.

Would this addition make more sense only for Ruby 2.4+?

**Comment by logicminds** [comment]
I can add 2.1 back to the matrix.  And update the gemspec as well.

**Comment by logicminds** [comment]
https://gitlab.com/puppet-debugger/puppet-debugger/-/jobs/300366206

Added 2.1 back to the matrix.  Only testing ruby 2.1 with puppet 4.10 since puppet 5 and 6 use 2.4. 

Will release puppet-debugger 0.14 with updated gemspec to force ruby >=2.1

**Comment by glennsarti** [comment]
Thanks @logicminds !!

**Pull request merged**
